Plugin:
  #### Cubit language ####
  locale: enEN
  #### Exclude worlds from cubitplugin ####
  #### example:  excluded-worlds: [world_nether, world_the_end]####
  excluded-worlds: []
  #### Config Version ####
  version: 1.0


##########################################
################Land module###############
##########################################
Land:
  # Max price for a land.
  max-tax-amount: 400.0
  
  # Taxes for every landbuy.
  tax-increase-per-region: 5.0
  
  # Price for the first region.
  first-region-costs: 120.0
  
  # Money back on land sell (default = 0.5 = 50% from the buyprice).
  percentage-at-region-sell: 0.5

  # Buyuptime for land member.
  buyup-members: 20.0

  # Buyuptime for outsiders.
  buyup-not-members: 35.0
  
  # Buyupinfo in days before buyable.
  buyup-info: 10
  
  # Border material on buy.
  land-buy-chunkBorders:
    material: TORCH
    
  # Border material on sell.
  land-sell-chunkBorders:
    material: REDSTONE_TORCH_ON

  # Price for a biomechange.
  setbiome: 300.0

  # Price for save a land (/lstore save).
  land-save: 300.0




##########################################
##############Database module#############
##########################################

  # MySQL-connection for regiondata/lastseen.
sql:
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  debugmode: false



##########################################
#################FTP module###############
##########################################

  # CubitFiles upload/download from a ftp server (For multiserver).
ftp:
  enable: false
  host: localhost
  port: 21
  username: ftpUser
  password: ftpPass

  

##########################################
#############CubitLimit module############
##########################################

CubitLimit:
  # Use the CubitLimit module (default true)
  enable: true
  # module properties
  properties:
  # Check a chunk upon load (ChunkLoadEvent).
    check-chunk-load: false
  
  # Check a chunk upon unload (ChunkUnloadEvent).
    check-chunk-unload: false
  
  # Check a chunk when a mob spawns (CreatureSpawnEvent).
    watch-creature-spawns: true
  
  # When a chunk is loaded, recheck it periodically. 
    active-inspections: true
  
  # How often, in seconds, to check the chunk.
    inspection-frequency: 300

# Spawn reasons to cull on.
  spawn-reasons:
    NATURAL: true
    JOCKEY: true
    CHUNK_GEN: true
    SPAWNER: true
    EGG: true
    SPAWNER_EGG: true
    LIGHTNING: true
    # These are deprecated, might not work in the future. 
    BED: true
    BUILD_SNOWMAN: true
    BUILD_IRONGOLEM: true
    BUILD_WITHER: true
    VILLAGE_DEFENSE: true
    VILLAGE_INVASION: true
    BREEDING: true
    SLIME_SPLIT: true
    REINFORCEMENTS: true
    CUSTOM: true
    DEFAULT: true

# This is the entity limit on a chunk (16x16).
  entities:
    ANIMAL: 50
    MONSTER: 50
    NPC: 50
    OTHER: 500
#   WATER_MOB: 5
#   AMBIENT: 5
#   CREEPER: 10
#   ...
#   Exclude these worlds from limits.  
  excluded-worlds: []