name: iLand
version: ${project.version}
description: iLand Regionmanager
author: Kekshaus
main: de.keks.iLand.ILandPlugin
depend: [WorldEdit, WorldGuard, Vault]
commands:
   land:
      description: Alle Land-Befehle
      usage: /<command>
   ladmin:
      description: Alle Land-Admin-Befehle
      usage: /<command>
permissions:
    iLand.admin:
        description: Alle Permissions
        children:
            iLand.land: true
            iLand.flags: true
            iLand.landEdit: true
            iLand.land.kickbypass: true
            iLand.admin.take: true
            iLand.admin.delete: true
            iLand.admin.help: true
            iLand.admin.reload: true
            iLand.admin.list: true
            iLand.admin.tp: true
            iLand.admin.unsetserverregion: true
            iLand.admin.setserverregion: true
            iLand.landEdit: true
            iLand.landEdit.regen: true
            iLand.landEdit.delete: true
    iLand.land:
        description: Alle Land Befehle
        children:
            iLand.land.help: true
            iLand.land.addmember: true
            iLand.land.removemember: true
            iLand.land.buy: true
            iLand.land.sell: true
            iLand.land.buyup: true
            iLand.land.info: true
            iLand.land.list: true
            iLand.land.offer: true
            iLand.land.give: true
            iLand.land.takeoffer: true
            iLand.land.kick: true
            iLand.land.version: true
            iLand.land.addallmember: true
            iLand.land.cleanmember: true
            iLand.land.removeallmember: true
    iLand.landEdit:
        description: Alle iChunk Commands
        children:
            iLand.landEdit.list: true
            iLand.landEdit.paste: true
            iLand.landEdit.save: true
            iLand.landEdit.help: true
            iLand.landEdit.biomes: true
            iLand.landEdit.setbiome: true
    iLand.flags:
        description: Gibt alle Flags frei
        children:
            iLand.flag.help: true
            iLand.flag.lock: true
            iLand.flag.mobs: true
            iLand.flag.potion: true
            iLand.flag.pvp: true
            iLand.flag.tnt: true
            iLand.flag.fire: true
    iLand.land.help:
        description: Haupt-Hilfeseite
        default: op
    iLand.land.addmember:
        description: Spieler hinzuf端gen
        default: op
    iLand.land.kick:
        description: Spieler verweisen
        default: op
    iLand.land.kickbypass:
        description: Landkick bypass
        default: op   
    iLand.land.removemember:
        description: Spieler entfernen
        default: op
    iLand.land.buy:
        description: Land kaufen
        default: op
    iLand.land.sell:
        description: Land verkaufen
        default: op
    iLand.land.buyup:
        description: Land aufkaufen
        default: op
    iLand.land.info:
        description: Land Informationen anzeigen
        default: op
    iLand.land.list:
        description: Laender auflisten
        default: op
    iLand.land.give:
        description: Land verschenken
        default: op
    iLand.land.offer:
        description: Land anbieten
        default: op
    iLand.land.takeoffer:
        description: Land abkaufen
        default: op
    iLand.land.version:
        description: iLand Version
        default: op
    iLand.land.addallmember:
        description: Land-Einstellungen zur端cksetzen
        default: op
    iLand.land.cleanmember:
        description: Land-Einstellungen zur端cksetzen
        default: op
    iLand.land.removeallmember:
        description: Land-Einstellungen zur端cksetzen
        default: op     
    iLand.flag.help:
        description: Flags-Hilfeseite
        default: op
    iLand.flag.lock:
        description: Flag abschliesen
        default: op
    iLand.flag.mobs:
        description: Flag Monster
        default: op
    iLand.flag.potion:
        description: Flag Wurftraenke
        default: op
    iLand.flag.pvp:
        description: Flag PvP
        default: op
    iLand.flag.tnt:
        description: Flag Explosionen
        default: op
    iLand.flag.fire:
        description: Flag Fire
        default: op
    iLand.admin.take:
        description: Admin Land uebername
        default: op
    iLand.admin.delete:
        description: Admin Land loeschen
        default: op
    iLand.admin.help:
        description: Ladmin Seite
        default: op
    iLand.admin.reload:
        description: Neuladen der iLand-Config
        default: op
    iLand.admin.setserverregion:
        description: Set a serverregion
        default: op
    iLand.admin.unsetserverregion:
        description: Unset a serverregion
        default: op
    iLand.admin.list:
        description: Auflisten von Regionen eines Spielers
        default: op
    iLand.admin.tp:
        description: Teleportierten zu einer Region
        default: op
    iLand.landEdit.delete:
        description: Delete a file
        default: op
    iLand.landEdit.list:
        description: List all your files
        default: op
    iLand.landEdit.paste:
        description: Paste a file
        default: op
    iLand.landEdit.save:
        description: Save a file
        default: op
    iLand.landEdit.regen:
        description: Regenerate a chunk
        default: op
    iLand.landEdit.biomes:
        description: Biome-Hilfeseite
        default: op
    iLand.landEdit.setbiome:
        description: Biome veraendern
        default: op
